# fly.toml app configuration file generated for lz-blog-builder on 2024-09-02T19:59:32-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lz-blog-builder'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
